// lib/events-data.ts

export interface EventData {
  slug: string
  image: string
  name: string
  type: string
  impact: string
  date: string
  location: string
  description: string
  content: string[]
  highlights: string[]
  gallery: string[]
  storySections?: {
    image: string
    title: string
    description: string
  }[]
  hasDetail?: boolean
}

export const eventsData: EventData[] = [
  // ============================================
  // MAIN EVENTS (DETAILED CONTENT)
  // ============================================
  
  // --- Brand Activation ---
  {
  slug: "above-and-beyond-open-house",
  image: "/images/beyoundbg.png",
  name: "Above and Beyond Open House",
  type: "Brand Activation",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Open house yang menjadi momen penting dalam perjalanan perusahaan, menghadirkan pengalaman acara yang hangat, terstruktur, dan berkesan bagi para tamu.",
  content: [
    "Above and Beyond Open House menjadi salah satu momen penting dalam perjalanan perusahaan, menghadirkan kesempatan bagi para tamu dan mitra untuk mengenal lebih dekat visi serta perkembangan yang telah dicapai.",
    "Acara ini dirancang dengan konsep open house yang fleksibel dan mengalir secara natural, memungkinkan para tamu untuk berinteraksi, berdiskusi, dan merasakan atmosfer kolaboratif yang menjadi nilai utama dari Clapham Collective.",
    "Dengan dukungan teknis yang optimal serta koordinasi tim yang solid, seluruh rangkaian acara berjalan tertata dengan baik dan menciptakan pengalaman yang hangat serta berkesan bagi setiap tamu yang hadir."
  ],
  highlights: [
    "Konsep open house yang fleksibel dan interaktif",
    "Interaksi langsung dengan tamu dan mitra",
    "Koordinasi acara yang tertata dengan baik",
    "Dukungan teknis profesional",
    "Momen penting dalam perjalanan perusahaan"
  ],
  gallery: [],
  hasDetail: true,
},
{
  slug: "above-and-beyond-seminar-100",
  image: "/images/Seminar-Above-and-Beyond.webp",
  name: "Seminar Above and Beyond Seminar",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seminar perdana yang berhasil melampaui target peserta dan menjadi fondasi kuat untuk program pengembangan berikutnya.",
  content: [
    "Above and Beyond Seminar menjadi seminar perdana yang diselenggarakan oleh klien dengan tujuan menghadirkan ruang berbagi pengetahuan dan inspirasi bagi para peserta.",
    "Acara ini berhasil menarik total 40 peserta, melampaui target awal yang telah direncanakan. Hal ini menunjukkan antusiasme yang tinggi dari peserta terhadap topik yang dibawakan.",
    "Dengan koordinasi tim yang rapi, eksekusi teknis yang berjalan baik, serta alur acara yang terkelola secara efektif, seminar ini berlangsung lancar dan menjadi fondasi kuat bagi pengembangan program-program selanjutnya."
  ],
  highlights: [
    "40 peserta hadir melampaui target awal",
    "Seminar perdana yang sukses terselenggara",
    "Koordinasi tim yang rapi dan profesional",
    "Eksekusi teknis acara berjalan lancar",
    "Fondasi kuat untuk program selanjutnya"
  ],
  gallery: [],
  hasDetail: true,
},

 

  // --- Seminar & Conference ---
  {
    slug: "clapham-conference-2025",
    image: "/images/event-conference-2025.webp",
    name: "Clapham Conference",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Konferensi yang mempertemukan pelaku usaha, profesional, dan komunitas untuk berbagi wawasan, membangun kolaborasi, dan mendorong perkembangan inovasi di kota Medan.",
content: [
  "Konferensi adalah sebuah forum pertemuan yang mempertemukan para profesional, pelaku usaha, akademisi, dan komunitas untuk berbagi pengetahuan, pengalaman, serta gagasan yang dapat mendorong kemajuan di berbagai bidang. Melalui sesi diskusi, presentasi, dan networking, konferensi menjadi ruang penting untuk bertukar perspektif, memperluas wawasan, dan membangun kolaborasi yang berdampak nyata.",

  "Clapham Conference hadir sebagai wadah kolaborasi yang mempertemukan peserta dari berbagai industri untuk saling belajar dan berkembang bersama. Acara ini menghadirkan pembicara inspiratif serta membuka ruang diskusi yang mendorong lahirnya ide-ide baru dan solusi yang relevan dengan tantangan dunia bisnis dan teknologi saat ini.",

  "Lebih dari sekadar acara berbagi pengetahuan, konferensi ini bertujuan memperkuat ekosistem inovasi di Kota Medan. Dengan mempertemukan pelaku usaha, startup, profesional, dan komunitas kreatif, Clapham Conference mendorong terciptanya kolaborasi yang dapat melahirkan peluang usaha baru, meningkatkan kualitas sumber daya manusia, serta mempercepat pertumbuhan ekonomi lokal.",

  "Melalui berbagai topik seperti teknologi, strategi bisnis, hingga perkembangan industri kreatif, konferensi ini diharapkan mampu menginspirasi generasi muda dan pelaku usaha untuk terus berinovasi. Dengan semangat kolaborasi dan pembelajaran bersama, Clapham Conference berkomitmen menjadi bagian dari upaya membangun kota yang lebih maju, adaptif, dan berkelanjutan."
],
highlights: [
  "Forum berbagi wawasan dan kolaborasi lintas industri",
  "Pembicara inspiratif dari berbagai bidang",
  "Diskusi dan networking antar pelaku usaha dan profesional",
  "Ruang lahirnya ide bisnis dan inovasi baru",
  "Mendorong pertumbuhan ekosistem bisnis di Kota Medan",
],
    storySections: [
      {
        image: "/images/1.avif",
        title: "Startup Medan 2016",
        description: "Startup dibangun dengan tujuan utama untuk menyelesaikan masalah nyata di masyarakat melalui solusi yang inovatif, efisien, dan scalable, biasanya dengan memanfaatkan teknologi atau model bisnis baru. Kehadiran startup di sebuah kota memberikan banyak manfaat, seperti menciptakan lapangan kerja baru, mendorong pertumbuhan ekonomi lokal, meningkatkan daya saing dan citra kota sebagai pusat inovasi, serta membangun ekosistem kreatif yang menghubungkan talenta, investor, dan pelaku usaha. Dengan demikian, startup tidak hanya menjadi mesin pertumbuhan bisnis, tetapi juga menjadi katalis perkembangan sosial dan ekonomi suatu kota secara berkelanjutan.",
      },
      {
        image: "/images/2.avif",
        title: "Startup medan 2018",
        description: "Event startup kali ini bertujuan menghadirkan inspirasi dan transfer pengetahuan dari perusahaan yang telah berkembang pesat seperti Bukalapak dan Gojek kepada para pelaku usaha, mahasiswa, dan komunitas kreatif di Kota Medan, sehingga tercipta ruang kolaborasi, pembelajaran, dan peluang nyata bagi lahirnya startup-startup baru yang inovatif dan berdaya saing. Dengan menghadirkan kisah perjalanan, strategi, serta tantangan yang pernah mereka hadapi, event ini diharapkan mampu memotivasi generasi muda, memperkuat ekosistem digital, menarik minat investor, serta mendorong pertumbuhan ekonomi lokal demi terwujudnya Kota Medan yang lebih maju, adaptif, dan berkelanjutan.",
      },
      {
        image: "/images/3.avif",
        title: "Startupfest 2019",
        description: "StartupFest lanjutan ini menjadi bukti nyata dari dampak event sebelumnya, di mana mulai bermunculan startup-startup baru hasil dari inspirasi, kolaborasi, dan jejaring yang telah terbangun. Jika sebelumnya fokus pada pembelajaran dan motivasi dari pelaku industri yang sudah berkembang, kini panggung diberikan kepada founder dan talenta lokal yang berani memulai serta menunjukkan progres usahanya. Event ini menegaskan bahwa Medan tidak lagi hanya menjadi penonton inovasi, tetapi mulai tumbuh sebagai pelaku aktif dalam membangun ekosistem startup yang berkelanjutan dan berdampak bagi kemajuan kota.",
      },
      {
        image: "/images/4.avif",
        title: "Clapham Conference 2022",
        description: "Clapham Conference kali ini berfokus pada penguatan manajemen bisnis dan keuangan sebagai fondasi utama pertumbuhan usaha yang berkelanjutan. Setelah sebelumnya mendorong lahirnya berbagai ide dan startup baru, kini acara ini mengarahkan perhatian pada bagaimana membangun sistem operasional yang profesional, strategi bisnis yang terukur, serta pengelolaan keuangan yang sehat agar usaha tidak hanya bertumbuh cepat, tetapi juga stabil dan tahan terhadap tantangan. Melalui pembahasan manajemen, cash flow, perencanaan keuangan, dan tata kelola bisnis, Clapham Conference diharapkan mampu membentuk pelaku usaha di Medan yang lebih siap, strategis, dan berdampak bagi perkembangan ekonomi kota.",
      },
      {
        image: "/images/5.avif",
        title: "Clapham Conference 2023",
        description: "Clapham Conference hadir dengan mengusung semangat Grow – Connect – Inspire, sebagai ruang bertemunya para pelaku usaha, profesional, dan calon founder untuk bertumbuh bersama dalam pemahaman manajemen bisnis dan keuangan yang lebih matang. Melalui sesi diskusi strategis, networking, dan berbagi pengalaman nyata, konferensi ini mendorong peserta untuk mengembangkan bisnis secara berkelanjutan (Grow), membangun jejaring kolaboratif yang kuat (Connect), serta saling menginspirasi dalam menciptakan dampak positif bagi ekosistem usaha di Kota Medan (Inspire).",
      },
      {
        image: "/images/6.avif",
        title: "Clapham Conference 2024",
        description: "Clapham Conference mengangkat isu bisnis yang adaptif terhadap perkembangan zaman dengan fokus pada pemanfaatan Artificial Intelligence (AI), strategi bisnis modern, dan digital marketing berbasis data. Mengusung semangat Connect & Correction, konferensi ini menjadi ruang bagi para pelaku usaha untuk membangun koneksi yang relevan sekaligus melakukan evaluasi serta penyempurnaan strategi agar tetap kompetitif di era digital. Dengan pendekatan teknologi dan analisis yang lebih cerdas, acara ini diharapkan mampu mendorong bisnis di Medan tumbuh lebih efisien, terukur, dan berkelanjutan.",
      },
      {
        image: "/images/7.jpg",
        title: "Clapham Conference 2025",
        description: "Clapham Conference kali ini mengangkat isu yang lebih fresh dan dinamis dengan fokus pada industri F&B yang sedang berkembang pesat, dipadukan dengan strategi bisnis dan teknologi modern. Mengusung semangat Taste & Unite, konferensi ini menjadi ruang pertemuan antara pelaku kuliner, entrepreneur, dan inovator teknologi untuk mengeksplorasi tren, efisiensi operasional, digitalisasi, hingga branding yang kuat di industri makanan dan minuman. Melalui kolaborasi dan pertukaran ide, acara ini diharapkan mampu memperkuat ekosistem bisnis F&B di Medan agar lebih kreatif, kompetitif, dan terhubung secara teknologi.",
      },
    ],
    gallery: [],
    hasDetail: true,
  },
   {
    slug: "brand-experience-festival",
    image: "/images/above-8.jpg",
    name: "Brand Experience Festival",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Festival pengalaman brand yang menciptakan interaksi mendalam antara brand dan audiens mereka.",
    content: [
      "Brand Experience Festival adalah event yang menggabungkan experiential marketing dengan entertainment untuk menciptakan pengalaman brand yang tak terlupakan. Dengan engagement rate mencapai 85% dari target audiens, festival ini membuktikan bahwa pendekatan experiential adalah cara paling efektif untuk membangun koneksi brand.",
      "Festival ini menghadirkan instalasi interaktif dari 12 brand ternama, masing-masing dirancang untuk mengajak pengunjung merasakan nilai dan cerita brand secara langsung. Dari virtual reality experience hingga hands-on workshop, setiap booth menawarkan sesuatu yang unik dan memorable.",
      "Tim Clapham Collective merancang setiap detail festival ini dengan cermat, mulai dari flow pengunjung, lighting design, hingga soundtrack yang mengiringi setiap zona. Hasilnya adalah sebuah pengalaman holistik yang tidak hanya menghibur tetapi juga meninggalkan kesan mendalam tentang setiap brand yang berpartisipasi.",
    ],
    highlights: [
      "12 brand dengan instalasi interaktif",
      "85% engagement rate dari target audiens",
      "Virtual reality brand experience",
      "Live performance dan entertainment",
      "Social media reach 2 juta+ impression",
    ],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "clapham-conference-2025-1",
    image: "/seminar&confrens/Active-Democracy.jpg",
    name: "Active Democracy",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "clapham-conference-2025-2",
    image: "/seminar&confrens/Brand-yourself-Nurture-your-Network.jpg",
    name: "Brand Yourself Nurture Your Network",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "clapham-conference-2025-3",
    image: "/seminar&confrens/Century-Learner.jpg",
    name: "Century Learner",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "clapham-conference-2025-4",
    image: "/seminar&confrens/Clapham-Conference.jpg",
    name: "Clapham Conference",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "clapham-conference-2025-5",
    image: "/seminar&confrens/Clapham-Conference2.jpg",
    name: "Clapham Conference",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "clapham-conference-2025-6",
    image: "/seminar&confrens/Clapham-Conversation-Market-that-Matters.jpg",
    name: "Clapham Conversation Market That Matters",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "clapham-conference-2025-7",
    image: "/seminar&confrens/Clapham-Conversation-Market-that-Matters2.jpg",
    name: "Clapham Conversation Market That Matters",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "clapham-conference-2025-8",
    image: "/seminar&confrens/Clapham-Conversation-Market-that-Matters3.jpg",
    name: "Clapham Conversation Market That Matters",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "clapham-conference-2025-9",
    image: "/seminar&confrens/Clapham-Conversation-Womens-Independence.jpg",
    name: "Clapham Conversation Womens Independence",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "clapham-conference-2025-10",
    image: "/seminar&confrens/Clapham-Conversation-Womens-Independence2.jpg",
    name: "Clapham Conversation Womens Independence",
    type: "Seminar & Conference",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
  slug: "clapham-conference-2025-11",
  image: "/seminar&confrens/Clapham-Startupfest.jpg",
  name: "Clapham Startupfest",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},
{
  slug: "clapham-conference-2025-12",
  image: "/seminar&confrens/Coffee-Talk.jpg",
  name: "Coffee Talk",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},
{
  slug: "clapham-conference-2025-13",
  image: "/seminar&confrens/Digital-Marketing.jpg",
  name: "Digital Marketing",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},

{
  slug: "clapham-conference-2025-15",
  image: "/seminar&confrens/FB-Dev-Circle.jpg",
  name: "FB Dev Circle",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},
{
  slug: "clapham-conference-2025-16",
  image: "/seminar&confrens/Higher-Education.jpg",
  name: "Higher Education",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},
{
  slug: "clapham-conference-2025-17",
  image: "/seminar&confrens/Infes-Aplaus2.jpg",
  name: "Infes Aplaus",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},
{
  slug: "clapham-conference-2025-18",
  image: "/seminar&confrens/JCH-Jump-Start.jpg",
  name: "JCH Jump Start",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},
{
  slug: "clapham-conference-2025-19",
  image: "/seminar&confrens/Scale-Up.jpg",
  name: "Scale Up",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},
{
  slug: "clapham-conference-2025-20",
  image: "/seminar&confrens/Seminar-Instagram.jpg",
  name: "Seminar Instagram",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},
{
  slug: "clapham-conference-2025-21",
  image: "/seminar&confrens/Startup-Fest.jpg",
  name: "Startup Fest",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},
{
  slug: "clapham-conference-2025-22",
  image: "/seminar&confrens/The-Art-of-Science-&-Networking.jpg",
  name: "The Art of Science & Networking",
  type: "Seminar & Conference",
  impact: "",
  date: "",
  location: "Clapham Collective, Medan",
  description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
  content: [],
  highlights: [],
  gallery: [],
  hasDetail: false,
},


  // --- Community Events (Detailed) ---
  {
    slug: "community-creative-gathering",
    image: "/images/above-6.jpg",
    name: "Community Creative Gathering",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Pertemuan komunitas kreatif yang menginspirasi kolaborasi dan ide-ide baru.",
    content: [
      "Community Creative Gathering adalah event rutin yang menjadi rumah bagi lebih dari 200 anggota komunitas kreatif aktif di Medan. Acara ini dirancang sebagai ruang aman dan inklusif bagi para kreator, desainer, seniman, dan inovator untuk bertemu, berbagi, dan berkolaborasi.",
      "Setiap pertemuan menghadirkan tema yang berbeda, mulai dari design thinking, creative entrepreneurship, hingga digital art dan photography. Format acara yang casual namun berstruktur memungkinkan peserta untuk belajar dari sesama kreator sambil membangun jaringan yang organik.",
      "Gathering ini telah melahirkan berbagai proyek kolaboratif yang sukses, mulai dari pameran seni bersama, zine community, hingga creative agency yang didirikan oleh anggota komunitas. Ini membuktikan bahwa ketika kreator bertemu dalam lingkungan yang tepat, hal-hal luar biasa bisa terjadi.",
    ],
    highlights: [
      "200+ anggota komunitas kreatif aktif",
      "Tema berbeda setiap pertemuan",
      "Open mic dan showcase session",
      "Collaborative project incubation",
      "Free access untuk semua kreator",
    ],
    gallery: [],
    hasDetail: true,
  },

  {
    slug: "creative-workshop-series",
    image: "/images/work-6.webp",
    name: "Creative Workshop Series",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [
      "Creative Workshop Series adalah program workshop bulanan yang telah berjalan sepanjang tahun 2024, menghadirkan 12 workshop dengan total lebih dari 400 peserta. Setiap bulan, workshop mengangkat topik yang berbeda untuk mengembangkan keterampilan praktis di bidang kreatif.",
      "Topik workshop mencakup spektrum luas dari dunia kreatif, mulai dari typography dan brand identity design, photography dan videography, creative writing, hingga UI/UX design dan motion graphics. Setiap workshop dipandu oleh praktisi berpengalaman yang aktif di industrinya.",
      "Yang membuat program ini istimewa adalah pendekatan hands-on yang diterapkan. Setiap peserta mengerjakan proyek nyata selama workshop dan pulang dengan portfolio piece yang bisa langsung digunakan. Banyak alumni workshop yang kemudian berhasil memulai karir kreatif mereka atau meningkatkan kualitas pekerjaan mereka secara signifikan.",
    ],
    highlights: [
      "12 topik berbeda sepanjang tahun",
      "Dipandu oleh praktisi industri",
      "Hands-on project di setiap sesi",
      "Portfolio piece untuk setiap peserta",
      "Alumni network 400+ kreator",
    ],
    gallery: [],
    hasDetail: false,
  },

  // ============================================
  // BRAND ACTIVATION SERIES (20 Events - Manual)
  // ============================================
  {
    slug: "brand-activation-1",
    image: "/images/brandacti/artwall-project.jpg",
    name: "Artwall Project",
    type: "Brand Activation",
    impact: " ",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-2",
    image: "/images/brandacti/BNI-Hackfest.jpg",
    name: "BNI Hackfest",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-3",
    image: "/images/brandacti/Bosch-Event.jpg",
    name: "Bosch Event",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-4",
    image: "/images/brandacti/Collaborative-WorkshopI.jpg",
    name: "Collaborative Workshop I",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-5",
    image: "/images/brandacti/Collaborative-WorkshopII.jpg",
    name: "Collaborative Workshop II",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-6",
    image: "/images/brandacti/Collaborative-WorkshopIII.jpg",
    name: "Collaborative Workshop III",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-7",
    image: "/images/brandacti/DSC-X-Roadshow.jpg",
    name: "DSC X Roadshow",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-8",
    image: "/images/brandacti/Gogames-Press-Conference.jpg",
    name: "GO games Press Conference",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-9",
    image: "/images/brandacti/JCI-Accounting.jpg",
    name: "JCI Accounting",
    type: "Brand Activation",
    impact: "",
    date: " ",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-10",
    image: "/images/brandacti/GoStartupIndonesia.jpg", // FIXED: Changed image path
    name: "Go Startup Indonesia", // FIXED: Changed name to differentiate
    type: "Brand Activation",
    impact: "",
    date: " ",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-11",
    image: "/images/brandacti/LOKET-Roadshow.jpg",
    name: "LOKET Roadshow",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-12",
    image: "/images/brandacti/Mobilkamu.jpg",
    name: "Mobilkamu",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-13",
    image: "/images/brandacti/NextDev-Talent-Scouting.jpg",
    name: "NextDev Talent Scouting",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-14",
    image: "/images/brandacti/SAP-Business-Suite-Innovation-Day.jpg",
    name: "SAP Business Suite Innovation Day",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-15",
    image: "/images/brandacti/Shopee.jpg",
    name: "Shopee",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-16",
    image: "/images/brandacti/Startup.jpg",
    name: "Startup",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-17",
    image: "/images/brandacti/UberxRailink.jpg",
    name: "Uber x Railink",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-18",
    image: "/images/brandacti/US-Biotek-Medan.jpg",
    name: "US Biotek Medan",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-19",
    image: "/images/brandacti/XL-Future-Leaders.jpg",
    name: "XL Future Leaders",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  

  // ============================================
  // COMMUNITY EVENTS SERIES (16 Events - Manual)
  // ============================================
  
  // --- Community Event Utama ---
  {
    slug: "bring-it-on", // FIXED: Changed from community-creative-1
    image: "/comunity/BRIng-It-On.jpg",
    name: "Bring It On",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },

  // --- Community Events Tambahan (15 events) ---
  {
    slug: "cinematography-class-monogatari", // FIXED: Changed from community-event-12
    image: "/comunity/Cinematography-Class-Monogatari.jpg",
    name: "Cinematography Class Monogatari",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-day-djarot-visit", // FIXED: Changed from community-event-3
    image: "/comunity/Community-Day-Djarot-Visit.jpg",
    name: "Community Day Djarot",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "ethan-zohn-turning-setback-into-comeback", // FIXED: Changed from community-event-4
    image: "/comunity/Ethan-Zohn -Turning-Setback-Into-Comeback.jpg",
    name: "Ethan Zohn - Turning Setback Into Comeback",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "executive-media-x-clapham", // FIXED: Changed from community-event-5
    image: "/comunity/Executive-Media-x-Clapham.jpg",
    name: "Executive Media x Clapham",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "fb-devc-merdeka-meetup", // FIXED: Changed from community-event-6
    image: "/comunity/FB-DevC-Merdeka-Meetup.jpg",
    name: "FB DevC Merdeka Meetup",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "geraldez", // FIXED: Changed from community-event-7
    image: "/comunity/Geraldez.jpg",
    name: "Geraldez",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "go-startup-indonesia", // FIXED: Changed from community-event-8
    image: "/comunity/GoStartupIndonesia.jpg",
    name: "Go Startup Indonesia",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "jci-medan", // FIXED: Changed from community-event-9
    image: "/comunity/JCI-Medan2.jpg",
    name: "JCI Medan",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "love-bonito-x-womandiri", // FIXED: Changed from community-event-10
    image: "/comunity/Love-Bonito-x-Womandiri.jpg",
    name: "Love Bonito x Womandiri",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "mikroskill-visit", // FIXED: Changed from community-event-11
    image: "/comunity/Mikroskill-Visit.jpg",
    name: "Mikroskill",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "movie-discussion-spotlight", // FIXED: Changed from community-event-12 (second instance)
    image: "/comunity/Movie-Discussion-Spotlight.jpg",
    name: "Movie Discussion Spotlight",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "mozilla-firefox", // FIXED: Changed from community-event-13
    image: "/comunity/Mozilla-Firefox-2.jpg",
    name: "Mozilla Firefox",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "pechakucha", // FIXED: Changed from community-event-14
    image: "/comunity/Pechakucha-vol-6-2.jpg",
    name: "Pechakucha",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "powerbox", // FIXED: Changed from community-event-15
    image: "/comunity/Powerbox.jpg",
    name: "Powerbox",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "ramadan-csr", // FIXED: Changed from community-event-16
    image: "/comunity/Ramadan-CSR.jpg",
    name: "Ramadan CSR",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "rumah-karya-indonesia-visit", // FIXED: Changed from community-event-17
    image: "/comunity/Rumah-Karya-Indonesia-visit.jpg",
    name: "Rumah Karya Indonesia ",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "sg-minister-visit", // FIXED: Changed from community-event-18
    image: "/comunity/SG-Minister-Visit.jpg",
    name: "SG Minister ",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "singapore-minister-of-trade-visit", // FIXED: Changed from community-event-19
    image: "/comunity/Singapore-Minister-of-Trade-Visit.jpg",
    name: "Singapore Minister of Trade ",
    type: "Community Event",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  
  // ============================================
  // WORKSHOP COMMUNITY SERIES (21 Events - Manual)
  // ============================================
  
  // --- Workshop Community Utama ---
  {
    slug: "akara-ivif", // FIXED: Changed from workshop-community-gathering
    image: "/workshopp/Akara-IVIF.jpg",
    name: "Akara IVIF",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },

  // --- Workshop Community Tambahan (20 events) ---
  {
    slug: "angin-medan", // FIXED: Changed from workshop-community-2
    image: "/workshopp/ANGIN-Medan.jpg",
    name: "ANGIN MEDAN",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "fbn-rotary", // FIXED: Changed from workshop-community-3
    image: "/workshopp/FBN-Rotary.jpg",
    name: "FNB Rotary",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "financial-workshop", // FIXED: Changed from workshop-community-4
    image: "/workshopp/Financial-Workshop.jpg",
    name: "Financial Workshop",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "international-breakfast-club", // FIXED: Changed from workshop-community-5
    image: "/workshopp/International-Breakfast-Club.jpg",
    name: "International Breakfast Club",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "investing", // FIXED: Changed from workshop-community-6
    image: "/workshopp/Investing.jpg",
    name: "Investing",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "jkt-denali-flog", // FIXED: Changed from workshop-community-7
    image: "/workshopp/JKT-Denali-Flog.jpg",
    name: "JKT Denali Flog",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "pakar-digital-workshop", // FIXED: Changed from workshop-community-8
    image: "/workshopp/Pakar-Digital-Workshop.jpg",
    name: "Pakar Digital Workshop",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "pakar-social-media-workshop", // FIXED: Changed from workshop-community-9
    image: "/workshopp/Pakar-Social-Media-Workshop.jpg",
    name: "Pakar Social Media-Workshop",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "sanrok-mike", // FIXED: Changed from workshop-community-10
    image: "/workshopp/Sanrok-Mike.jpg",
    name: "Sanrok-Mike",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "sml-one-ongoing-courses", // FIXED: Changed from workshop-community-11
    image: "/workshopp/SML-One-Ongoing-courses.jpg",
    name: "SMLONE On going Courses",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "smlone-orator-signature-pro-workshop", // FIXED: Changed from workshop-community-12
    image: "/workshopp/SMLONE-Orator-Signature-Pro-Workshop.jpg",
    name: "SMLONE Orator Signature Pro Workshop",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "startup-clinic-growth", // FIXED: Changed from workshop-community-13
    image: "/workshopp/Startup-Clinic-Growth.jpg",
    name: "Startup Clinic Growth",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "startup-grind", // FIXED: Changed from workshop-community-14
    image: "/workshopp/Startup-Grind.jpg",
    name: "Startup Grind",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "teachers-workshop", // FIXED: Changed from workshop-community-15
    image: "/workshopp/Teachers-Workshop.jpg",
    name: "Teachers Workshop",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "worksho-fbn", // FIXED: Changed from workshop-community-16
    image: "/workshopp/Worksho-FBN.jpg",
    name: "Worksho FBN",
    type: "Workshop",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  
  // ============================================
  // GATHERING SERIES (9 Events - Manual)
  // ============================================
  {
    slug: "gathering-series-1", // FIXED: Changed to unique slug
    image: "/getring/Annual-Dinner.webp",
    name: "Annual Dinner Clapham",
    type: "Gathering",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-2", // FIXED: Changed to unique slug
    image: "/getring/Annual-Dinner2.webp",
    name: "Annual Dinner Clapham 2",
    type: "Gathering",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-3", // FIXED: Changed to unique slug
    image: "/getring/Clapham Anniv.jpg",
    name: "Clapham Anniversary",
    type: "Gathering",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-4", // FIXED: Changed to unique slug
    image: "/getring/Clapham-Conversation.jpg",
    name: "Clapham Conversation: Bisa Buat Apa Ya Untuk Medan",
    type: "Gathering",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-5", // FIXED: Changed to unique slug
    image: "/getring/Hari-Pendidikan-Nasional-Clapham.png",
    name: "Hari Pendidikan Nasional Clapham",
    type: "Gathering",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-6", // FIXED: Changed to unique slug
    image: "/getring/Member-Gathering-Clapham.jpg",
    name: "Member Gathering Clapham",
    type: "Gathering",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-7", // FIXED: Changed to unique slug
    image: "/getring/Members-Gathering-Clapham.jpg",
    name: "Member Gathering Clapham 2",
    type: "Gathering",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-8", // FIXED: Changed to unique slug
    image: "/getring/Members-Gathering.jpg",
    name: "Members Gathering Clapham 3",
    type: "Gathering",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-9", // FIXED: Changed to unique slug
    image: "/getring/Musicaly.jpg",
    name: "Musicaly",
    type: "Gathering",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
]

// ============================================
// HELPER FUNCTIONS
// ============================================

export function filterEventsByType(type: string): EventData[] {
  if (!type || type.toLowerCase() === "all") return eventsData
  return eventsData.filter(
    (event) => event.type.trim().toLowerCase() === type.trim().toLowerCase()
  )
}

export function getEventBySlug(slug: string): EventData | undefined {
  return eventsData.find((event) => event.slug === slug)
}

export function getAllEventSlugs(): string[] {
  return eventsData.map((event) => event.slug)
}

// Optional: Debug functions (you can remove these if not needed)
export function checkDuplicateSlugs() {
  const slugs = eventsData.map(e => e.slug)
  const duplicates = slugs.filter((slug, index) => slugs.indexOf(slug) !== index)
  if (duplicates.length > 0) {
    console.warn('Duplicate slugs found:', [...new Set(duplicates)])
  } else {
    console.log('No duplicate slugs found')
  }
}

export function checkDuplicateImages() {
  const images = eventsData.map(e => e.image)
  const duplicates = images.filter((img, index) => images.indexOf(img) !== index)
  if (duplicates.length > 0) {
    console.warn('Duplicate images found:', [...new Set(duplicates)])
  } else {
    console.log('No duplicate images found')
  }
}