// lib/events-data.ts

export interface EventData {
  slug: string
  image: string
  name: string
  type: string
  impact: string
  date: string
  location: string
  description: string
  content: string[]
  highlights: string[]
  gallery: string[]
  storySections?: {
    image: string
    title: string
    description: string
  }[]
  hasDetail?: boolean
}

export const eventsData: EventData[] = [
  // ============================================
  // MAIN EVENTS (DETAILED CONTENT)
  // ============================================
  
  // --- Brand Activation ---
  {
    slug: "above-and-beyond-seminar",
    image: "/images/beyoundbg.png",
    name: "Above and Beyond Seminar",
    type: "Brand Activation",
    impact: "Kolaborasi dengan 8 brand nasional",
    date: "22 Januari 2025",
    location: "Clapham Collective, Medan",
    description: "Seminar intensif yang membahas strategi inovatif untuk pertumbuhan bisnis dan personal.",
    content: [
      "Above and Beyond Seminar adalah program seminar intensif yang dirancang khusus untuk para profesional dan pelaku bisnis yang ingin melampaui batasan konvensional. Acara ini berhasil menghadirkan kolaborasi dengan 8 brand nasional terkemuka yang masing-masing memberikan perspektif unik tentang strategi pertumbuhan.",
      "Seminar ini menghadirkan sesi-sesi mendalam tentang personal branding, digital marketing strategy, dan leadership development. Setiap sesi dirancang untuk memberikan takeaway yang langsung dapat diimplementasikan oleh peserta dalam karir dan bisnis mereka.",
      "Dengan format yang menggabungkan presentasi, panel diskusi, dan sesi tanya jawab interaktif, peserta mendapatkan pengalaman belajar yang komprehensif. Para pembicara dari berbagai brand nasional berbagi studi kasus nyata dan strategi yang telah terbukti berhasil di pasar Indonesia.",
    ],
    highlights: [
      "8 brand nasional sebagai collaborator",
      "Workshop personal branding intensif",
      "Panel diskusi dengan CEO dan founder",
      "Sertifikat profesional untuk peserta",
      "Akses ke materi eksklusif pasca-acara",
    ],
    gallery: [],
    hasDetail: true,
  },

  {
    slug: "brand-experience-festival",
    image: "/images/above-8.jpg",
    name: "Brand Experience Festival",
    type: "Brand Activation",
    impact: "Engagement rate 85% dari target audiens",
    date: "20 Oktober 2024",
    location: "Clapham Collective, Medan",
    description: "Festival pengalaman brand yang menciptakan interaksi mendalam antara brand dan audiens mereka.",
    content: [
      "Brand Experience Festival adalah event yang menggabungkan experiential marketing dengan entertainment untuk menciptakan pengalaman brand yang tak terlupakan. Dengan engagement rate mencapai 85% dari target audiens, festival ini membuktikan bahwa pendekatan experiential adalah cara paling efektif untuk membangun koneksi brand.",
      "Festival ini menghadirkan instalasi interaktif dari 12 brand ternama, masing-masing dirancang untuk mengajak pengunjung merasakan nilai dan cerita brand secara langsung. Dari virtual reality experience hingga hands-on workshop, setiap booth menawarkan sesuatu yang unik dan memorable.",
      "Tim Clapham Collective merancang setiap detail festival ini dengan cermat, mulai dari flow pengunjung, lighting design, hingga soundtrack yang mengiringi setiap zona. Hasilnya adalah sebuah pengalaman holistik yang tidak hanya menghibur tetapi juga meninggalkan kesan mendalam tentang setiap brand yang berpartisipasi.",
    ],
    highlights: [
      "12 brand dengan instalasi interaktif",
      "85% engagement rate dari target audiens",
      "Virtual reality brand experience",
      "Live performance dan entertainment",
      "Social media reach 2 juta+ impression",
    ],
    gallery: [],
    hasDetail: true,
  },

  // --- Seminar & Conference ---
  {
    slug: "clapham-conference-2025",
    image: "/images/event-conference-2025.JPG",
    name: "Clapham Conference",
    type: "Seminar & Conference",
    impact: "500+ peserta dari 15 industri berbeda",
    date: "15 Maret 2025",
    location: "Clapham Collective, Medan",
    description: "Konferensi tahunan yang menghadirkan pembicara terkemuka dan ratusan peserta dari berbagai industri.",
    content: [
      "Clapham Conference 2025 adalah konferensi tahunan terbesar yang diselenggarakan oleh Clapham Collective, menghadirkan lebih dari 500 peserta dari 15 industri berbeda di seluruh Indonesia. Acara ini menjadi wadah pertemuan para profesional, entrepreneur, dan pemimpin industri untuk berbagi wawasan dan membangun koneksi yang bermakna.",
      "Tahun ini, konferensi mengambil tema 'Shaping Tomorrow' dengan fokus pada inovasi teknologi, kepemimpinan transformatif, dan strategi bisnis berkelanjutan. Para pembicara terkemuka dari berbagai bidang memberikan presentasi yang menginspirasi dan workshop interaktif yang memberikan nilai praktis bagi setiap peserta.",
      "Selama dua hari penuh, peserta mendapatkan akses ke lebih dari 20 sesi paralel, 5 keynote speech, dan networking session yang dirancang khusus untuk memfasilitasi kolaborasi lintas industri. Feedback dari peserta menunjukkan tingkat kepuasan 96%, menjadikan ini salah satu konferensi paling sukses yang pernah kami selenggarakan.",
    ],
    highlights: [
      "20+ sesi paralel dengan topik beragam",
      "5 keynote speaker dari pemimpin industri",
      "Networking dinner eksklusif",
      "Exhibition area dengan 30+ booth partner",
      "Live streaming untuk peserta virtual",
    ],
    storySections: [
      {
        image: "/images/1.avif",
        title: "Startup Medan 2016",
        description: "Startup dibangun dengan tujuan utama untuk menyelesaikan masalah nyata di masyarakat melalui solusi yang inovatif, efisien, dan scalable, biasanya dengan memanfaatkan teknologi atau model bisnis baru. Kehadiran startup di sebuah kota memberikan banyak manfaat, seperti menciptakan lapangan kerja baru, mendorong pertumbuhan ekonomi lokal, meningkatkan daya saing dan citra kota sebagai pusat inovasi, serta membangun ekosistem kreatif yang menghubungkan talenta, investor, dan pelaku usaha. Dengan demikian, startup tidak hanya menjadi mesin pertumbuhan bisnis, tetapi juga menjadi katalis perkembangan sosial dan ekonomi suatu kota secara berkelanjutan.",
      },
      {
        image: "/images/2.avif",
        title: "Startup medan 2018",
        description: "Event startup kali ini bertujuan menghadirkan inspirasi dan transfer pengetahuan dari perusahaan yang telah berkembang pesat seperti Bukalapak dan Gojek kepada para pelaku usaha, mahasiswa, dan komunitas kreatif di Kota Medan, sehingga tercipta ruang kolaborasi, pembelajaran, dan peluang nyata bagi lahirnya startup-startup baru yang inovatif dan berdaya saing. Dengan menghadirkan kisah perjalanan, strategi, serta tantangan yang pernah mereka hadapi, event ini diharapkan mampu memotivasi generasi muda, memperkuat ekosistem digital, menarik minat investor, serta mendorong pertumbuhan ekonomi lokal demi terwujudnya Kota Medan yang lebih maju, adaptif, dan berkelanjutan.",
      },
      {
        image: "/images/3.avif",
        title: "Startupfest 2019",
        description: "StartupFest lanjutan ini menjadi bukti nyata dari dampak event sebelumnya, di mana mulai bermunculan startup-startup baru hasil dari inspirasi, kolaborasi, dan jejaring yang telah terbangun. Jika sebelumnya fokus pada pembelajaran dan motivasi dari pelaku industri yang sudah berkembang, kini panggung diberikan kepada founder dan talenta lokal yang berani memulai serta menunjukkan progres usahanya. Event ini menegaskan bahwa Medan tidak lagi hanya menjadi penonton inovasi, tetapi mulai tumbuh sebagai pelaku aktif dalam membangun ekosistem startup yang berkelanjutan dan berdampak bagi kemajuan kota.",
      },
      {
        image: "/images/4.avif",
        title: "Clapham Conference 2022",
        description: "Clapham Conference kali ini berfokus pada penguatan manajemen bisnis dan keuangan sebagai fondasi utama pertumbuhan usaha yang berkelanjutan. Setelah sebelumnya mendorong lahirnya berbagai ide dan startup baru, kini acara ini mengarahkan perhatian pada bagaimana membangun sistem operasional yang profesional, strategi bisnis yang terukur, serta pengelolaan keuangan yang sehat agar usaha tidak hanya bertumbuh cepat, tetapi juga stabil dan tahan terhadap tantangan. Melalui pembahasan manajemen, cash flow, perencanaan keuangan, dan tata kelola bisnis, Clapham Conference diharapkan mampu membentuk pelaku usaha di Medan yang lebih siap, strategis, dan berdampak bagi perkembangan ekonomi kota.",
      },
      {
        image: "/images/5.avif",
        title: "Clapham Conference 2023",
        description: "Clapham Conference hadir dengan mengusung semangat Grow – Connect – Inspire, sebagai ruang bertemunya para pelaku usaha, profesional, dan calon founder untuk bertumbuh bersama dalam pemahaman manajemen bisnis dan keuangan yang lebih matang. Melalui sesi diskusi strategis, networking, dan berbagi pengalaman nyata, konferensi ini mendorong peserta untuk mengembangkan bisnis secara berkelanjutan (Grow), membangun jejaring kolaboratif yang kuat (Connect), serta saling menginspirasi dalam menciptakan dampak positif bagi ekosistem usaha di Kota Medan (Inspire).",
      },
      {
        image: "/images/6.avif",
        title: "Clapham Conference 2024",
        description: "Clapham Conference mengangkat isu bisnis yang adaptif terhadap perkembangan zaman dengan fokus pada pemanfaatan Artificial Intelligence (AI), strategi bisnis modern, dan digital marketing berbasis data. Mengusung semangat Connect & Correction, konferensi ini menjadi ruang bagi para pelaku usaha untuk membangun koneksi yang relevan sekaligus melakukan evaluasi serta penyempurnaan strategi agar tetap kompetitif di era digital. Dengan pendekatan teknologi dan analisis yang lebih cerdas, acara ini diharapkan mampu mendorong bisnis di Medan tumbuh lebih efisien, terukur, dan berkelanjutan.",
      },
      {
        image: "/images/7.jpg",
        title: "Clapham Conference 2025",
        description: "Clapham Conference kali ini mengangkat isu yang lebih fresh dan dinamis dengan fokus pada industri F&B yang sedang berkembang pesat, dipadukan dengan strategi bisnis dan teknologi modern. Mengusung semangat Taste & Unite, konferensi ini menjadi ruang pertemuan antara pelaku kuliner, entrepreneur, dan inovator teknologi untuk mengeksplorasi tren, efisiensi operasional, digitalisasi, hingga branding yang kuat di industri makanan dan minuman. Melalui kolaborasi dan pertukaran ide, acara ini diharapkan mampu memperkuat ekosistem bisnis F&B di Medan agar lebih kreatif, kompetitif, dan terhubung secara teknologi.",
      },
    ],
    gallery: [],
    hasDetail: true,
  },

  // --- Community Events (Detailed) ---
  {
    slug: "community-creative-gathering",
    image: "/images/above-6.jpg",
    name: "Community Creative Gathering",
    type: "Community Event",
    impact: "200+ anggota komunitas kreatif aktif",
    date: "8 Februari 2025",
    location: "Clapham Collective, Medan",
    description: "Pertemuan komunitas kreatif yang menginspirasi kolaborasi dan ide-ide baru.",
    content: [
      "Community Creative Gathering adalah event rutin yang menjadi rumah bagi lebih dari 200 anggota komunitas kreatif aktif di Medan. Acara ini dirancang sebagai ruang aman dan inklusif bagi para kreator, desainer, seniman, dan inovator untuk bertemu, berbagi, dan berkolaborasi.",
      "Setiap pertemuan menghadirkan tema yang berbeda, mulai dari design thinking, creative entrepreneurship, hingga digital art dan photography. Format acara yang casual namun berstruktur memungkinkan peserta untuk belajar dari sesama kreator sambil membangun jaringan yang organik.",
      "Gathering ini telah melahirkan berbagai proyek kolaboratif yang sukses, mulai dari pameran seni bersama, zine community, hingga creative agency yang didirikan oleh anggota komunitas. Ini membuktikan bahwa ketika kreator bertemu dalam lingkungan yang tepat, hal-hal luar biasa bisa terjadi.",
    ],
    highlights: [
      "200+ anggota komunitas kreatif aktif",
      "Tema berbeda setiap pertemuan",
      "Open mic dan showcase session",
      "Collaborative project incubation",
      "Free access untuk semua kreator",
    ],
    gallery: [],
    hasDetail: true,
  },

  {
    slug: "creative-workshop-series",
    image: "/images/work-6.JPG",
    name: "Creative Workshop Series",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [
      "Creative Workshop Series adalah program workshop bulanan yang telah berjalan sepanjang tahun 2024, menghadirkan 12 workshop dengan total lebih dari 400 peserta. Setiap bulan, workshop mengangkat topik yang berbeda untuk mengembangkan keterampilan praktis di bidang kreatif.",
      "Topik workshop mencakup spektrum luas dari dunia kreatif, mulai dari typography dan brand identity design, photography dan videography, creative writing, hingga UI/UX design dan motion graphics. Setiap workshop dipandu oleh praktisi berpengalaman yang aktif di industrinya.",
      "Yang membuat program ini istimewa adalah pendekatan hands-on yang diterapkan. Setiap peserta mengerjakan proyek nyata selama workshop dan pulang dengan portfolio piece yang bisa langsung digunakan. Banyak alumni workshop yang kemudian berhasil memulai karir kreatif mereka atau meningkatkan kualitas pekerjaan mereka secara signifikan.",
    ],
    highlights: [
      "12 topik berbeda sepanjang tahun",
      "Dipandu oleh praktisi industri",
      "Hands-on project di setiap sesi",
      "Portfolio piece untuk setiap peserta",
      "Alumni network 400+ kreator",
    ],
    gallery: [],
    hasDetail: true,
  },

  // ============================================
  // BRAND ACTIVATION SERIES (20 Events - Manual)
  // ============================================
  {
    slug: "brand-activation-1",
    image: "/images/brandacti/artwall-project.jpg",
    name: "Artwall Project",
    type: "Brand Activation",
    impact: " ",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-2",
    image: "/images/brandacti/BNI-Hackfest.jpg",
    name: "BNI Hackfest",
    type: "Brand Activation",
    impact: "",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-3",
    image: "/images/brandacti/Bosch-Event.jpg",
    name: "Bosch Event",
    type: "Brand Activation",
    impact: "",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-4",
    image: "/images/brandacti/Collaborative-WorkshopI.jpg",
    name: "Collaborative Workshop I",
    type: "Brand Activation",
    impact: "",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-5",
    image: "/images/brandacti/Collaborative-WorkshopII.jpg",
    name: "Collaborative Workshop II",
    type: "Brand Activation",
    impact: "",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-6",
    image: "/images/brandacti/Collaborative-WorkshopIII.jpg",
    name: "Collaborative Workshop III",
    type: "Brand Activation",
    impact: "",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-7",
    image: "/images/brandacti/DSC-X-Roadshow.jpg",
    name: "DSC X Roadshow",
    type: "Brand Activation",
    impact: "",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-8",
    image: "/images/brandacti/Gogames-Press-Conference.jpg",
    name: "GOgames Press Conference",
    type: "Brand Activation",
    impact: "",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-9",
    image: "/images/brandacti/JCI-Accounting.jpg",
    name: "JCI Accounting",
    type: "Brand Activation",
    impact: "",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-10",
    image: "/images/brandacti/JCI-Accounting.jpg",
    name: "JCI Accounting",
    type: "Brand Activation",
    impact: "",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-11",
    image: "/images/brandacti/LOKET-Roadshow.jpg",
    name: "LOKET Roadshow",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-12",
    image: "/images/brandacti/Mobilkamu.jpg",
    name: "Mobilkamu",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-13",
    image: "/images/brandacti/NextDev-Talent-Scouting.jpg",
    name: "NextDev Talent Scouting",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-14",
    image: "/images/brandacti/SAP-Business-Suite-Innovation-Day.jpg",
    name: "SAP Business Suite Innovation Day",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-15",
    image: "/images/brandacti/Shopee.jpg",
    name: "Shopee",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-16",
    image: "/images/brandacti/Startup.jpg",
    name: "Startup",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-17",
    image: "/images/brandacti/UberxRailink.jpg",
    name: "Uber x Railink",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-18",
    image: "/images/brandacti/US-Biotek-Medan.jpg",
    name: "US Biotek Medan",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "brand-activation-19",
    image: "/images/brandacti/XL-Future-Leaders.jpg",
    name: "XL Future Leaders",
    type: "Brand Activation",
    impact: "",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  

  // ============================================
  // COMMUNITY EVENTS SERIES (16 Events - Manual)
  // ============================================
  
  // --- Community Event Utama ---
  {
    slug: "comunity-creative-gathering",
    image: "/comunity/Community1.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },

  // --- Community Events Tambahan (15 events) ---
  {
    slug: "community-event-1",
    image: "/comunity/Community1.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-2",
    image: "/comunity/Community2.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-3",
    image: "/comunity/Community3.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-4",
    image: "/comunity/Community4.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-5",
    image: "/comunity/Community5.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-6",
    image: "/comunity/Community6.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-7",
    image: "/comunity/Community7.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-8",
    image: "/comunity/Community8.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-9",
    image: "/comunity/Community9.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-10",
    image: "/comunity/Community10.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-11",
    image: "/comunity/Community11.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-12",
    image: "/comunity/Community12.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-13",
    image: "/comunity/Community13.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-14",
    image: "/comunity/Community14.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "community-event-15",
    image: "/comunity/Community15.jpg",
    name: "Community Creative",
    type: "Community Event",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  // ============================================
  // WORKSHOP COMMUNITY SERIES (21 Events - Manual)
  // ============================================
  
  // --- Workshop Community Utama ---
  {
    slug: "workshop-community-gathering",
    image: "/workshopp/Workshop-1.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },

  // --- Workshop Community Tambahan (20 events) ---
  {
    slug: "workshop-community-2",
    image: "/workshopp/Workshop-2.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-3",
    image: "/workshopp/Workshop-3.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-4",
    image: "/workshopp/Workshop-4.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-5",
    image: "/workshopp/Workshop-5.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-6",
    image: "/workshopp/Workshop-6.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-7",
    image: "/workshopp/Workshop-7.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-8",
    image: "/workshopp/Workshop-8.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-9",
    image: "/workshopp/Workshop-9.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-10",
    image: "/workshopp/Workshop-10.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-11",
    image: "/workshopp/Workshop-11.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-12",
    image: "/workshopp/Workshop-12.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-13",
    image: "/workshopp/Workshop-13.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-14",
    image: "/workshopp/Workshop-14.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-15",
    image: "/workshopp/Workshop-15.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-16",
    image: "/workshopp/Workshop-16.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-17",
    image: "/workshopp/Workshop-17.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-18",
    image: "/workshopp/Workshop-18.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-19",
    image: "/workshopp/Workshop-19.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-20",
    image: "/workshopp/Workshop-20.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "workshop-community-21",
    image: "/workshopp/Workshop-21.jpg",
    name: "Workshop Community",
    type: "Workshop",
    impact: "Ruang kreatif untuk ide dan kolaborasi baru",
    date: "",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },

  // ============================================
  // GATHERING SERIES (9 Events - Manual)
  // ============================================
  {
    slug: "gathering-series-clapham-1",
    image: "/getring/Gathering1.jpg",
    name: "Gathering Series Clapham",
    type: "Gathering",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-clapham-2",
    image: "/getring/Gathering2.png",
    name: "Gathering Series Clapham",
    type: "Gathering",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-clapham-3",
    image: "/getring/Gathering3.jpg",
    name: "Gathering Series Clapham",
    type: "Gathering",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-clapham-4",
    image: "/getring/Gathering4.jpg",
    name: "Gathering Series Clapham",
    type: "Gathering",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-clapham-5",
    image: "/getring/Gathering5.jpg",
    name: "Gathering Series Clapham",
    type: "Gathering",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-clapham-6",
    image: "/getring/Gathering6.jpg",
    name: "Gathering Series Clapham",
    type: "Gathering",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-clapham-7",
    image: "/getring/Gathering7.jpg",
    name: "Gathering Series Clapham",
    type: "Gathering",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-clapham-8",
    image: "/getring/Gathering8.JPG",
    name: "Gathering Series Clapham",
    type: "Gathering",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
  {
    slug: "gathering-series-clapham-9",
    image: "/getring/Gathering9.JPG",
    name: "Gathering Series Clapham",
    type: "Gathering",
    impact: "12 workshop, 400+ peserta sepanjang tahun",
    date: "Januari - Desember 2024",
    location: "Clapham Collective, Medan",
    description: "Seri workshop kreatif bulanan yang mengembangkan keterampilan praktis dan mendorong ekspresi kreatif.",
    content: [],
    highlights: [],
    gallery: [],
    hasDetail: false,
  },
]

// ============================================
// HELPER FUNCTIONS
// ============================================

export function filterEventsByType(type: string): EventData[] {
  if (!type || type.toLowerCase() === "all") return eventsData
  return eventsData.filter(
    (event) => event.type.trim().toLowerCase() === type.trim().toLowerCase()
  )
}

export function getEventBySlug(slug: string): EventData | undefined {
  return eventsData.find((event) => event.slug === slug)
}

export function getAllEventSlugs(): string[] {
  return eventsData.map((event) => event.slug)
}